### ISSUE TITLE
Cant able to Load the models

### ISSUE THREAD

**Issue by RajatDBazaar** [nmfisher/thermion_examples#2]
D/ProfileInstaller( 9230): Installing profile for app.polyvox.example
E/flutter ( 9230): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9230): #0      ExampleWidgetState.build.<anonymous closure> (package:thermion_flutter_example/main.dart:172:34)
E/flutter ( 9230): #1      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
E/flutter ( 9230): #2      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
E/flutter ( 9230): #3      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
E/flutter ( 9230): #4      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283:7)
E/flutter ( 9230): #5      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169:27)
E/flutter ( 9230): #6      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:506:20)
E/flutter ( 9230): #7      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482:22)
E/flutter ( 9230): #8      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457:11)
E/flutter ( 9230): #9      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
E/flutter ( 9230): #10     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
E/flutter ( 9230): #11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
E/flutter ( 9230): #12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
E/flutter ( 9230): #13     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter ( 9230): #14     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
E/flutter ( 9230): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
E/flutter ( 9230):

**Comment by nmfisher** [comment]
@RajatDBazaar  as I mentioned in the other issue, I'm in the process of updating the sample projects (and I will actually merge this repository into the main `thermion` repository). Give me a few days to get onto it.

**Comment by RajatDBazaar** [comment]
Sure I will wait for it!!
